//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.15 at 01:18:12 AM CET 
//


package fr.insee.xml.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.insee.xml.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SIRET_QNAME = new QName("http://xml.insee.fr/schema", "SIRET");
    private final static QName _SIREN_QNAME = new QName("http://xml.insee.fr/schema", "SIREN");
    private final static QName _NIC_QNAME = new QName("http://xml.insee.fr/schema", "NIC");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.insee.xml.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SIRETCtype }
     * 
     */
    public SIRETCtype createSIRETCtype() {
        return new SIRETCtype();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SIRETCtype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.insee.fr/schema", name = "SIRET")
    public JAXBElement<SIRETCtype> createSIRET(SIRETCtype value) {
        return new JAXBElement<SIRETCtype>(_SIRET_QNAME, SIRETCtype.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.insee.fr/schema", name = "SIREN")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSIREN(String value) {
        return new JAXBElement<String>(_SIREN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.insee.fr/schema", name = "NIC")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNIC(String value) {
        return new JAXBElement<String>(_NIC_QNAME, String.class, null, value);
    }

}
