//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.15 at 01:18:12 AM CET 
//


package fr.gouv.interieur.actes_v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Donnees contenues dans une enveloppe de transmission collectivité vers MISILL
 * 
 * <p>Java class for DonneesEnveloppeCLMISILL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DonneesEnveloppeCLMISILL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Emetteur">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.interieur.gouv.fr/ACTES#v1.1-20040216}IDCL"/>
 *                   &lt;element ref="{http://www.interieur.gouv.fr/ACTES#v1.1-20040216}Referent" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AdressesRetour">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="Email" type="{http://www.interieur.gouv.fr/ACTES#v1.1-20040216}Email"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.interieur.gouv.fr/ACTES#v1.1-20040216}FormulairesEnvoyes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DonneesEnveloppeCLMISILL", propOrder = {
    "emetteur",
    "adressesRetour",
    "formulairesEnvoyes"
})
public class DonneesEnveloppeCLMISILL {

    @XmlElement(name = "Emetteur", required = true)
    protected DonneesEnveloppeCLMISILL.Emetteur emetteur;
    @XmlElement(name = "AdressesRetour", required = true)
    protected DonneesEnveloppeCLMISILL.AdressesRetour adressesRetour;
    @XmlElement(name = "FormulairesEnvoyes", required = true)
    protected FormulairesEnvoyes formulairesEnvoyes;

    /**
     * Gets the value of the emetteur property.
     * 
     * @return
     *     possible object is
     *     {@link DonneesEnveloppeCLMISILL.Emetteur }
     *     
     */
    public DonneesEnveloppeCLMISILL.Emetteur getEmetteur() {
        return emetteur;
    }

    /**
     * Sets the value of the emetteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link DonneesEnveloppeCLMISILL.Emetteur }
     *     
     */
    public void setEmetteur(DonneesEnveloppeCLMISILL.Emetteur value) {
        this.emetteur = value;
    }

    /**
     * Gets the value of the adressesRetour property.
     * 
     * @return
     *     possible object is
     *     {@link DonneesEnveloppeCLMISILL.AdressesRetour }
     *     
     */
    public DonneesEnveloppeCLMISILL.AdressesRetour getAdressesRetour() {
        return adressesRetour;
    }

    /**
     * Sets the value of the adressesRetour property.
     * 
     * @param value
     *     allowed object is
     *     {@link DonneesEnveloppeCLMISILL.AdressesRetour }
     *     
     */
    public void setAdressesRetour(DonneesEnveloppeCLMISILL.AdressesRetour value) {
        this.adressesRetour = value;
    }

    /**
     * Liste des fichiers XML envoyés
     * 
     * @return
     *     possible object is
     *     {@link FormulairesEnvoyes }
     *     
     */
    public FormulairesEnvoyes getFormulairesEnvoyes() {
        return formulairesEnvoyes;
    }

    /**
     * Liste des fichiers XML envoyés
     * 
     * @param value
     *     allowed object is
     *     {@link FormulairesEnvoyes }
     *     
     */
    public void setFormulairesEnvoyes(FormulairesEnvoyes value) {
        this.formulairesEnvoyes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="Email" type="{http://www.interieur.gouv.fr/ACTES#v1.1-20040216}Email"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "email"
    })
    public static class AdressesRetour {

        @XmlElement(name = "Email", required = true)
        protected List<String> email;

        /**
         * Gets the value of the email property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the email property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEmail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getEmail() {
            if (email == null) {
                email = new ArrayList<String>();
            }
            return this.email;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.interieur.gouv.fr/ACTES#v1.1-20040216}IDCL"/>
     *         &lt;element ref="{http://www.interieur.gouv.fr/ACTES#v1.1-20040216}Referent" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "idcl",
        "referent"
    })
    public static class Emetteur {

        @XmlElement(name = "IDCL", required = true)
        protected IDCL idcl;
        @XmlElement(name = "Referent")
        protected Referent referent;

        /**
         * Gets the value of the idcl property.
         * 
         * @return
         *     possible object is
         *     {@link IDCL }
         *     
         */
        public IDCL getIDCL() {
            return idcl;
        }

        /**
         * Sets the value of the idcl property.
         * 
         * @param value
         *     allowed object is
         *     {@link IDCL }
         *     
         */
        public void setIDCL(IDCL value) {
            this.idcl = value;
        }

        /**
         * Gets the value of the referent property.
         * 
         * @return
         *     possible object is
         *     {@link Referent }
         *     
         */
        public Referent getReferent() {
            return referent;
        }

        /**
         * Sets the value of the referent property.
         * 
         * @param value
         *     allowed object is
         *     {@link Referent }
         *     
         */
        public void setReferent(Referent value) {
            this.referent = value;
        }

    }

}
